import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-50">
      <Head>
        <title>ExamReady - AI-Powered Certification Prep</title>
        <meta name="description" content="Practice for tech certification exams with AI-generated questions" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4 py-16">
        <div className="text-center mb-16">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">ExamReady</h1>
          <p className="text-xl text-gray-600 mb-8">
            Prepare for your tech certification exams with AI-generated practice questions
          </p>
          <div className="flex justify-center gap-4">
            <Link href="/exams" className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-medium">
              Start Practice
            </Link>
            <Link href="/about" className="bg-gray-200 hover:bg-gray-300 text-gray-800 px-6 py-3 rounded-lg font-medium">
              Learn More
            </Link>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-8 mb-16">
          <div className="bg-white p-6 rounded-lg shadow">
            <h2 className="text-xl font-semibold mb-4">Realistic Questions</h2>
            <p className="text-gray-600">Practice with questions that mimic the style and difficulty of real certification exams.</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow">
            <h2 className="text-xl font-semibold mb-4">AI-Generated Content</h2>
            <p className="text-gray-600">Get unlimited unique practice questions generated by our AI system.</p>
          </div>
          <div className="bg-white p-6 rounded-lg shadow">
            <h2 className="text-xl font-semibold mb-4">Performance Tracking</h2>
            <p className="text-gray-600">Monitor your progress and focus on areas that need improvement.</p>
          </div>
        </div>

        <div className="bg-white p-8 rounded-lg shadow">
          <h2 className="text-2xl font-semibold mb-4">Available Certification Tracks</h2>
          <ul className="grid md:grid-cols-2 gap-4">
            <li className="p-4 border rounded hover:bg-gray-50 cursor-pointer">AWS Certified Solutions Architect</li>
            <li className="p-4 border rounded hover:bg-gray-50 cursor-pointer">Microsoft Azure Administrator</li>
            <li className="p-4 border rounded hover:bg-gray-50 cursor-pointer">Google Cloud Professional</li>
            <li className="p-4 border rounded hover:bg-gray-50 cursor-pointer">CompTIA Security+</li>
          </ul>
        </div>
      </main>

      <footer className="bg-gray-800 text-white py-8">
        <div className="container mx-auto px-4 text-center">
          <p>© {new Date().getFullYear()} ExamReady. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}